// SQLite equivalent of schema.js. Datetimes are stored as UTC "YYYY-MM-DD HH:MM:SS" text.
const table = (name, body) => `CREATE TABLE IF NOT EXISTS ${name} (${body})`;
const touch = (name) => `CREATE TRIGGER IF NOT EXISTS trg_${name}_updated AFTER UPDATE ON ${name}
  FOR EACH ROW WHEN NEW.updated_at = OLD.updated_at
  BEGIN UPDATE ${name} SET updated_at = datetime('now') WHERE id = NEW.id; END`;
const ts = `created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`;

export const sqliteSchema = [
  table('users', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE COLLATE NOCASE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'editor' CHECK (role IN ('admin','editor')),
    avatar TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    last_login_at TEXT,
    ${ts}`),

  `CREATE TABLE IF NOT EXISTS settings (
    "key" TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (datetime('now')))`,

  table('blog_categories', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    meta_title TEXT,
    meta_description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    ${ts}`),

  table('blogs', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT,
    cover_image TEXT,
    cover_image_alt TEXT,
    category_id INTEGER REFERENCES blog_categories(id) ON DELETE SET NULL,
    tags TEXT,
    author_name TEXT,
    author_role TEXT,
    author_bio TEXT,
    author_avatar TEXT,
    author_url TEXT,
    reviewed_by TEXT,
    reviewer_credentials TEXT,
    last_reviewed_at TEXT,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','scheduled')),
    is_featured INTEGER NOT NULL DEFAULT 0,
    published_at TEXT,
    reading_time INTEGER NOT NULL DEFAULT 1,
    word_count INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    meta_title TEXT,
    meta_description TEXT,
    focus_keyword TEXT,
    secondary_keywords TEXT,
    canonical_url TEXT,
    og_title TEXT,
    og_description TEXT,
    og_image TEXT,
    robots_index INTEGER NOT NULL DEFAULT 1,
    robots_follow INTEGER NOT NULL DEFAULT 1,
    schema_type TEXT NOT NULL DEFAULT 'BlogPosting',
    faqs TEXT,
    custom_schema TEXT,
    created_by INTEGER,
    updated_by INTEGER,
    ${ts}`),
  'CREATE INDEX IF NOT EXISTS idx_blogs_status_published ON blogs (status, published_at)',
  'CREATE INDEX IF NOT EXISTS idx_blogs_category ON blogs (category_id)',

  table('clients', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    location TEXT,
    logo TEXT,
    website TEXT,
    industry TEXT,
    is_healthcare INTEGER NOT NULL DEFAULT 0,
    show_on_map INTEGER NOT NULL DEFAULT 1,
    map_x REAL,
    map_y REAL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    ${ts}`),

  table('videos', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    youtube_id TEXT NOT NULL,
    category TEXT,
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT,
    duration TEXT,
    thumbnail TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    ${ts}`),

  table('testimonials', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    role TEXT,
    company TEXT,
    content TEXT NOT NULL,
    avatar TEXT,
    rating INTEGER NOT NULL DEFAULT 5,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    ${ts}`),

  table('faqs', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    page TEXT NOT NULL DEFAULT 'home',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    ${ts}`),

  table('jobs', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    department TEXT,
    location TEXT,
    employment_type TEXT,
    work_mode TEXT,
    experience TEXT,
    salary_range TEXT,
    openings INTEGER NOT NULL DEFAULT 1,
    summary TEXT,
    description TEXT,
    responsibilities TEXT,
    requirements TEXT,
    benefits TEXT,
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed','draft')),
    deadline TEXT,
    meta_title TEXT,
    meta_description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    ${ts}`),

  table('job_applications', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER REFERENCES jobs(id) ON DELETE SET NULL,
    job_title TEXT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    experience TEXT,
    current_company TEXT,
    portfolio_url TEXT,
    linkedin_url TEXT,
    cover_letter TEXT,
    resume_path TEXT,
    resume_original_name TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','reviewing','shortlisted','rejected','hired')),
    notes TEXT,
    ${ts}`),

  table('contact_messages', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT,
    email TEXT NOT NULL,
    phone TEXT,
    company TEXT,
    service TEXT,
    message TEXT NOT NULL,
    source_page TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','read','replied','archived')),
    notes TEXT,
    ip TEXT,
    user_agent TEXT,
    ${ts}`),

  table('subscribers', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE COLLATE NOCASE,
    status TEXT NOT NULL DEFAULT 'subscribed' CHECK (status IN ('subscribed','unsubscribed')),
    source TEXT,
    ${ts}`),

  table('media', `
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filename TEXT NOT NULL,
    original_name TEXT,
    url TEXT NOT NULL,
    mime TEXT,
    size INTEGER,
    width INTEGER,
    height INTEGER,
    alt TEXT,
    folder TEXT NOT NULL DEFAULT 'general',
    uploaded_by INTEGER,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))`),

  ...['users', 'blog_categories', 'blogs', 'clients', 'videos', 'testimonials', 'faqs', 'jobs', 'job_applications', 'contact_messages', 'subscribers'].map(touch),
  `CREATE TRIGGER IF NOT EXISTS trg_settings_updated AFTER UPDATE ON settings
    FOR EACH ROW WHEN NEW.updated_at = OLD.updated_at
    BEGIN UPDATE settings SET updated_at = datetime('now') WHERE "key" = NEW."key"; END`,
];
